# Generated by Django 5.2.3 on 2025-09-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('main', 'Main'), ('top', 'Top')], max_length=20, unique=True)),
                ('products', models.ManyToManyField(blank=True, related_name='featured_in', to='shop.product')),
            ],
            options={
                'verbose_name': 'Featured collection',
                'verbose_name_plural': 'Featured collections',
            },
        ),
    ]
